apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: polyglot-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: polyglot-shop/shipping-service:latest
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: shipping-service-config
            - secretRef:
                name: shipping-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: polyglot-shop
spec:
  selector:
    app: shipping-service
  ports:
    - port: 8005
      targetPort: 8005
  type: ClusterIP
