apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: polyglot-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: polyglot-shop/payment-service:latest
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: payment-service-config
            - secretRef:
                name: payment-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: polyglot-shop
spec:
  selector:
    app: payment-service
  ports:
    - port: 8004
      targetPort: 8004
  type: ClusterIP
