apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-redis
  namespace: polyglot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-redis
  template:
    metadata:
      labels:
        app: payment-redis
    spec:
      containers:
        - name: payment-redis
          image: redis:7
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
      volumes:
        - name: redis-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: payment-redis
  namespace: polyglot-shop
spec:
  selector:
    app: payment-redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
