apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: polyglot-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: polyglot-shop/product-service:latest
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: polyglot-shop
spec:
  selector:
    app: product-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
