apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: polyglot-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: polyglot-shop/auth-service:latest
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: polyglot-shop
spec:
  selector:
    app: auth-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
