apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
  namespace: polyglot-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
        - name: inventory-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-service-secret
                  key: SA_PASSWORD
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: inventory-db-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: inventory-db-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  namespace: polyglot-shop
spec:
  selector:
    app: inventory-db
  ports:
    - port: 1433
      targetPort: 1433
  type: ClusterIP
