apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: polyglot-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: polyglot-shop/inventory-service:latest
          ports:
            - containerPort: 8006
          envFrom:
            - configMapRef:
                name: inventory-service-config
            - secretRef:
                name: inventory-service-secret
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: polyglot-shop
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8006
      targetPort: 8006
  type: ClusterIP
